schema_version = "1.0.0"

id = "AutoRatio"
name = "AutoRatio"
tagline = "Adjust Resolution based on given Aspect Ratio"
version = "1.0.0"
type = "add-on"
maintainer = "Shino Mythmaker"
license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "4.2.0"
blender_version_max = "4.6.0"
website = "https://github.com/ShinoMythmaker/Auto-Ratio"
tags = ["Output"]



